apiVersion: v1
kind: Service
metadata:
  name: fast-api-service    # Do not change this name
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    name: fastapi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-backend
spec:
  selector:
    matchLabels:
      name: fastapi 
  template:
    metadata:
      labels:
        name: fastapi
    spec:
      containers:
      - name: fast-api-backend
        image: fast-api-backend:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          protocol: TCP
