apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-ctr
          image: docker.io/cse4100/kubernetes-custom-nginx:1.0
          resources:
            limits:
              memory: "16Mi"
              cpu: "100m"
          volumeMounts:
            - name: auth
              mountPath: "/etc/auth"
              readOnly: true
      volumes:
        - name: auth
          secret:
            secretName: nginx-auth
---
apiVersion: v1
kind: Service
metadata:
  name: css-secret-web-server
spec:
  selector:
    app: nginx 
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-secret: nginx-auth
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret-type: auth-map
spec:
  ingressClassName: nginx-example
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: css-secret-web-server
            port:
              number: 8080
