apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      # tells the deployment to manage pods labeled app=nginx
      app: nginx
  # tells the deployment to run 2 pods matching the template
  replicas: 2
  template:
    metadata:
      labels:
        # tells the pods to have label app=nginx
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        volumeMounts:
        - name: pages-volume
          mountPath: /usr/share/nginx/html
      volumes:
        - name: pages-volume
          configMap:
            name: pages

